Resources:
  
  LocationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.locationTableName}
      AttributeDefinitions:
        - AttributeName: name
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: name
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE        
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}